In [50]:
%reload_ext autoreload
%autoreload 2
import logic_circuit
import numpy as np
import pandas as pd

state0 = np.array([0, 0, 0, 0, 0])
params = {'w': 0.25, 'B': 0.5, 'alpha' : 0.5}

fed_circuit = logic_circuit.Circuit(state0, params, fed=True)
fed_circuit.search_fixed_point()

Fixed point reached in 4 steps.


array([1, 0, 1, 1, 1])

In [51]:
starved_circuit = logic_circuit.Circuit(state0, params, fed=False)
starved_circuit.search_fixed_point()

Fixed point reached in 6 steps.


array([0, 1, 2, 0, 2])

In [52]:
#initialized 8 diofferent circuits with different perturbations, 4 fed and 4 starved, package as dictionary
fed_a = logic_circuit.Circuit(state0, params, fed=True)
fed_a.inactive_csd()

starved_a = logic_circuit.Circuit(state0, params, fed=False)
starved_a.inactive_csd()

fed_b = logic_circuit.Circuit(state0, params, fed=True)
fed_b.inactivep_LN14()

starved_b = logic_circuit.Circuit(state0, params, fed=False)
starved_a.inactivep_LN14()

fed_c = logic_circuit.Circuit(state0, params, fed=True)
fed_c.block_pln0_14()

starved_c = logic_circuit.Circuit(state0, params, fed=False)
starved_c.block_pln0_14()

fed_d = logic_circuit.Circuit(state0, params, fed=True)
fed_d.block_pln14_0()

starved_d = logic_circuit.Circuit(state0, params, fed=False)
starved_d.block_pln14_0()

#package as a dictionary
circuits = {'Fed A': fed_a, 'Starved A': starved_a,
            'Fed B': fed_b, 'Starved B': starved_b,
            'Fed C': fed_c, 'Starved C': starved_c,
            'Fed D': fed_d, 'Starved D': starved_d}

#initialize a dictionary to store final states
final_states = {key: None for key in circuits.keys()}
#run search_fixed_point for each circuit in the dictionary

for key, circ in circuits.items():
    state = circ.search_fixed_point() #runs search, returns fixed points, prints output as well
    final_states[key] = np.append(state, circ.y()) #store final states in dictionary

[[ 0.   -1.   -0.25 -0.25 -0.25]
 [-0.25  0.   -0.25 -1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]
[[ 0.   -1.   -0.25 -0.25 -0.25]
 [-0.25  0.   -0.25 -1.    0.  ]
 [ 0.    0.    0.    0.    1.  ]
 [ 0.    0.    0.    0.    0.  ]
 [ 0.    0.    0.    0.    0.  ]]
Fixed point reached in 4 steps.
Fixed point reached in 4 steps.
Fixed point reached in 4 steps.
Fixed point reached in 6 steps.
Fixed point reached in 4 steps.
Fixed point reached in 6 steps.
Fixed point reached in 3 steps.
Fixed point reached in 4 steps.


In [53]:
#organizes the final results in a table
df = pd.DataFrame.from_dict(final_states, orient='index', columns=['uPN', 'mPN', 'LN0', 'LN14', 'CSD', 'y'])
df.index.name = 'Perturbation'
display(df)


uPN  mPN  LN0  LN14  CSD  y
Perturbation                             
Fed A           1    0    1     1    1 -1
Starved A       1    0    1     1    1 -1
Fed B           1    0    1     1    1 -1
Starved B       0    1    2     0    2  1
Fed C           1    0    1     1    1 -1
Starved C       0    1    2     0    2  1
Fed D           1    1    1     0    1  1
Starved D       0    1    2     0    2  1

To do: run the 4 perturbations for fed and starved, generate 4 tables like in the pset